[wokwi]
version = 1
firmware = '.pio/build/esp32cam/firmware.bin'
elf = '.pio/build/esp32cam/firmware.elf'

[[net.forward]]
from = "localhost:8180"
to = "target:80"

[[chip]]
name = "i2c-mock"
binary = "chips/i2c-mock.chip.wasm"
json = "chips/i2c-mock.chip.json"